version: "latest"

services:
  dinedesign:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dinedesign-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run dev